### ISSUE TITLE
Add verb `get` to methods?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/get-east-asian-width#5]
```diff
- import {eastAsianWidth, eastAsianWidthType} from 'get-east-asian-width';
+ import {getEastAsianWidth, getEastAsianWidthType} from 'get-east-asian-width';
```

**Comment by sindresorhus** [comment]
I generally leave out `get` unless it's required to make it clear. Even if I agreed, it would not be worth doing a major release for this.

The package name having `get` is just so that I could publish it. `east-asian-width` and `unicode-east-asian-width` were taken.
